# Generated by Django 4.2 on 2023-05-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_thread_options_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated',
        ),
    ]
