# Generated by Django 4.2 on 2023-06-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_thread_options_thread_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('N', 'No Leído'), ('L', 'Leído')], default='N', max_length=1),
        ),
    ]
