# Generated by Django 4.2 on 2023-06-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_thread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('N', 'No Leído'), ('L', 'Leído')], default='N', max_length=1),
        ),
    ]
