# Generated by Django 4.2.2 on 2023-07-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_alter_thread_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='status',
        ),
    ]
